Repository cool-people-make-things/smart-shopper, pull requests merged in 2025-08, with the labels that each got.

#101 chore: 100 - husky config fix
  .husky/pre-commit
  .husky/pre-push
  backend/spec/requests/search_controller_spec.rb
  frontend/src/components/Card/Card.test.tsx
  frontend/src/compositions/Featured/Featured.test.tsx
  frontend/src/pages/Home/Home.test.tsx
Labels: chore

#99 chore: 40 - parse wls html
  backend/app/controllers/search_controller.rb
  backend/app/services/woolworths_parser.rb
  backend/spec/fixtures/wls_curated.html
  backend/spec/fixtures/wls_curated.json
  backend/spec/services/woolworths_parser_spec.rb
Labels: chore

#116 chore: global types
  frontend/src/context/CartContext.tsx
  frontend/src/context/utils/initialCart.ts
  frontend/src/types/Cart.types.d.ts
  frontend/src/types/Price.types.d.ts
  frontend/src/types/Product.types.d.ts
  frontend/src/types/Promo.types.d.ts
Labels: chore

#115 chore: localStorage utils
  frontend/src/context/utils/localStorage.test.ts
  frontend/src/context/utils/localStorage.ts
Labels: chore

#126 chore: #117 - pns parser tests
  backend/app/services/paknsave_parser.rb
  backend/bin/run_tests
  backend/spec/fixtures/pns_curated.html
  backend/spec/fixtures/pns_curated.rb
  backend/spec/services/paknsave_parser_spec.rb
Labels: chore

#129 chore: #105 - backend refinement
  backend/app/controllers/search_controller.rb
  backend/app/helpers/log.rb
  backend/app/services/data_manager.rb
  backend/app/services/new_world_parser.rb
  backend/app/services/paknsave_parser.rb
  backend/app/services/web_scraper.rb
  backend/app/services/woolworths_parser.rb
  backend/spec/fixtures/pns_curated.rb
  backend/spec/fixtures/wls_curated.json
Labels: chore

#133 chore: #110 - parser checks and consistency updates
  backend/Dockerfile
  backend/app/services/new_world_parser.rb
  backend/app/services/paknsave_parser.rb
  backend/app/services/woolworths_parser.rb
  backend/spec/fixtures/pns_curated.html
  backend/spec/fixtures/pns_curated.rb
  backend/spec/fixtures/wls_curated.html
  backend/spec/fixtures/wls_curated.json
  backend/spec/services/paknsave_parser_spec.rb
  backend/spec/services/woolworths_parser_spec.rb
  frontend/src/types/Price.types.d.ts
  frontend/src/types/Product.types.d.ts
Labels: chore

#132 chore: #4 - rename api route
  backend/README.md
  backend/app/assets/images/.keep
  backend/app/assets/stylesheets/application.css
  backend/app/controllers/api/v1/search_controller.rb
  backend/app/controllers/search_controller.rb
  backend/app/services/data_manager.rb
  backend/config/routes.rb
  backend/lib/tasks/.keep
  backend/script/.keep
  backend/spec/requests/search_controller_spec.rb
  backend/tmp/.keep
  backend/vendor/.keep
  frontend/src/api/search.test.ts
  frontend/src/api/search.ts
Labels: documentation, chore

#134 chore #121 - add item to cartcontext
  frontend/src/context/CartContext.test.tsx
  frontend/src/context/CartContext.tsx
  frontend/src/context/utils/devInitialCart.ts
  frontend/src/context/utils/localStorage.test.ts
  frontend/src/context/utils/renderComponentWithCart.tsx
  frontend/src/lib/test/fixtures/cart.ts
  frontend/src/types/Cart.types.d.ts
  frontend/src/types/Supermarket.types.d.ts
Labels: chore

#136 chore #127 - adr updates
  doc/adr/0008-search-query-in-browser-url.md
  doc/adr/0009-search-results-in-context.md
  doc/adr/0010-cart-stored-in-obj.md
Labels: documentation, chore

#141 update cart item quantity
  frontend/src/context/CartContext.test.tsx
  frontend/src/context/CartContext.tsx
  frontend/src/lib/test/fixtures/cart.ts
Labels: chore

#146 chore: #145 - individual supermarket cart composition
  frontend/src/compositions/IndividualSupermarketCart/IndividualSupermarketCart.test.tsx
  frontend/src/compositions/IndividualSupermarketCart/IndividualSupermarketCart.tsx
  frontend/src/compositions/IndividualSupermarketCart/index.ts
  frontend/src/pages/Cart/Cart.tsx
Labels: chore

#151 [Release] feat: #107 - cart context
  frontend/src/context/CartContext.test.tsx
  frontend/src/context/CartContext.tsx
  frontend/src/context/utils/cartData.ts
  frontend/src/context/utils/localStorage.test.ts
  frontend/src/context/utils/localStorage.ts
  frontend/src/context/utils/renderComponentWithCart.tsx
  frontend/src/lib/test/fixtures/cart.ts
  frontend/src/types/Cart.types.d.ts
  frontend/src/types/Supermarket.types.d.ts
Labels: feature

#147 [Release] chore: #91 - nw scrape improvements
  backend/.gitignore
  backend/Gemfile
  backend/Gemfile.lock
  backend/app/services/data_manager.rb
  backend/app/services/new_world_parser.rb
  backend/app/services/web_scraper.rb
  backend/spec/fixtures/nw_curated.html
  backend/spec/fixtures/nw_curated.rb
  backend/spec/rails_helper.rb
  backend/spec/services/data_manager_spec.rb
  backend/spec/services/new_world_parser_spec.rb
  backend/spec/services/web_scraper_spec.rb
Labels: chore

#154 chore: #153 - cart totals
  frontend/src/context/CartContext.test.tsx
  frontend/src/context/CartContext.tsx
  frontend/src/context/utils/calculateTotals.test.ts
  frontend/src/context/utils/calculateTotals.ts
  frontend/src/context/utils/cartData.ts
  frontend/src/context/utils/localStorage.ts
  frontend/src/lib/test/fixtures/calculatedCosts.ts
  frontend/src/lib/test/fixtures/cart.ts
  frontend/src/lib/test/fixtures/products/index.ts
  frontend/src/lib/test/fixtures/products/nwProducts.ts
  frontend/src/lib/test/fixtures/products/pnsProducts.ts
  frontend/src/lib/test/fixtures/products/wlsProducts.ts
  frontend/src/lib/test/vitest.setup.ts
  frontend/src/types/Cart.types.d.ts
  frontend/vite.config.ts
Labels: chore

#156 feat: #144 - cart component
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/retroui/Label.tsx
  frontend/src/components/retroui/index.tsx
  frontend/src/compositions/CartProduct/CartProduct.test.tsx
  frontend/src/compositions/CartProduct/CartProduct.tsx
  frontend/src/compositions/CartProduct/index.ts
  frontend/src/compositions/IndividualSupermarketCart/IndividualSupermarketCart.test.tsx
  frontend/src/compositions/IndividualSupermarketCart/IndividualSupermarketCart.tsx
  frontend/src/compositions/IndividualSupermarketCart/index.ts
  frontend/src/pages/Cart/Cart.test.tsx
  frontend/src/pages/Cart/Cart.tsx
Labels: feature

#160 chore #135 - ShopCode type
  frontend/src/hooks/useSearchAllSupermarkets.ts
  frontend/src/hooks/useSearchAllSupermarkets.utils.test.ts
  frontend/src/hooks/useSearchAllSupermarkets.utils.ts
  frontend/src/lib/test/fixtures/cart.ts
  frontend/src/types/Product.types.d.ts
  frontend/src/types/Supermarket.types.d.ts
Labels: chore

#162 chore: #159 - card details add to cart button functionality
  frontend/src/components/Card/Card.test.tsx
  frontend/src/components/Card/Card.tsx
  frontend/src/components/CardDetails/CardDetails.test.tsx
  frontend/src/components/CardDetails/CardDetails.tsx
  frontend/src/components/ProductColumn/ProductColumn.tsx
  frontend/src/compositions/Featured/Featured.tsx
  frontend/src/context/CartContext.tsx
Labels: chore
