Repository cool-people-make-things/smart-shopper, pull requests merged in 2025-07, with the labels that each got.

#15 chore: 12 - update repo templates
  .github/ISSUE_TEMPLATE/custom-issue-template.md
  .github/pull_request_template.md
Labels: chore

#18 chore: 9 - adds types for frontend
  app/frontend/types/Cart.types.d.ts
  app/frontend/types/Price.types.d.ts
  app/frontend/types/Product.types.d.ts
  app/frontend/types/Promo.types.d.ts
Labels: chore

#22 chore: #20 - remove vite from backend
  backend/Gemfile
  backend/Gemfile.lock
  backend/README.md
  backend/app/frontend/components/App.tsx
  backend/app/frontend/entrypoints/_FYI.md
  backend/app/frontend/entrypoints/application.tsx
  backend/app/views/layouts/application.html.erb
  backend/app/views/pages/home.html.erb
  backend/config/vite.json
  backend/package-lock.json
  backend/package.json
  backend/tsconfig.json
  backend/vite.config.ts
Labels: chore

#43 chore: #41 - update response data format
  backend/app/assets/data/nw.json
  backend/app/assets/data/pns.json
  backend/app/assets/data/wls.json
  backend/app/controllers/search_controller.rb
Labels: chore

#61 feat: #3 - basic home page template created
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Home.tsx
  frontend/src/components/retroui/Card.tsx
  frontend/src/components/retroui/Input.tsx
  frontend/src/components/retroui/Sonner.tsx
  frontend/src/components/retroui/Text.tsx
  frontend/src/components/retroui/index.tsx
Labels: feature

#57 chore: #30 - scrape NW webpage
  backend/.gitignore
  backend/Gemfile
  backend/Gemfile.lock
  backend/app/controllers/search_controller.rb
  backend/app/services/web_scraper.rb
Labels: chore

#63 feat: #28 - featured component
  frontend/src/App.tsx
  frontend/src/components/Home.tsx
  frontend/src/compositions/Featured/Featured.test.tsx
  frontend/src/compositions/Featured/Featured.tsx
  frontend/src/compositions/Featured/index.ts
  frontend/src/pages/Home/Home.test.tsx
  frontend/src/pages/Home/Home.tsx
  frontend/src/pages/Home/index.ts
Labels: feature

#71 chore: #24 - organise all readme docs
  README.md
  backend/README.md
  backend/_FYI.md
  backend/app/controllers/_FYI.md
  backend/app/views/layouts/_FYI.md
  backend/app/views/pages/_FYI.md
  backend/config/_FYI.md
  docs/architecture/0001-record-architecture-decisions.md
  docs/readme/ADR-tooling.md
  docs/readme/Install-ruby-rails.md
  frontend/LICENSE.md
  frontend/README.md
  frontend/public/icons/smart-shopper.png
  frontend/public/icons/vite.svg
Labels: documentation, chore

#73 chore: #45 - CardDetails component
  frontend/src/components/Card/Card.test.tsx
  frontend/src/components/Card/Card.tsx
  frontend/src/components/CardDetails/CardDetails.test.tsx
  frontend/src/components/CardDetails/CardDetails.tsx
  frontend/src/components/CardDetails/index.ts
Labels: chore

#56 [Release] feat: 5 - new world scrape
  backend/.gitignore
  backend/Dockerfile
  backend/Gemfile
  backend/Gemfile.lock
  backend/README.md
  backend/app/assets/data/nw.json
  backend/app/assets/data/nw.jsx
  backend/app/controllers/search_controller.rb
  backend/app/services/data_manager.rb
  backend/app/services/new_world_parser.rb
  backend/app/services/web_scraper.rb
  backend/bin/dev
  backend/docker-compose.yml
  docs/readme/Install-docker.md
  docs/readme/Install-ruby-rails.md
  frontend/src/types/Price.types.d.ts
  frontend/src/types/Promo.types.d.ts
Labels: feature

#83 chore: #39 woolworths web scrape
  backend/Gemfile.lock
  backend/app/controllers/search_controller.rb
  backend/app/services/web_scraper.rb
  frontend/src/components/Card/Card.tsx
  frontend/src/components/CardDetails/CardDetails.test.tsx
  frontend/src/components/CardDetails/CardDetails.tsx
Labels: chore

#86 chore: #81 - adr update
  README.md
  backend/README.md
  doc/adr/0001-record-architecture-decisions.md
  doc/adr/0002-splitting-the-front-from-back.md
  doc/adr/0003-selenium.md
  doc/adr/0004-docker.md
  doc/adr/0005-rufo-vs-rubocop.md
  doc/adr/0006-class-vs-instance.md
  doc/adr/0007-ruby-yard-comments.md
  doc/readme/ADR-tooling.md
  doc/readme/Install-docker.md
  doc/readme/Install-ruby-rails.md
  doc/readme/YARD-comments.md
Labels: chore

#89 rewrite rb comments to match style
  backend/app/controllers/search_controller.rb
  backend/app/services/data_manager.rb
  backend/app/services/new_world_parser.rb
  backend/app/services/web_scraper.rb
  doc/readme/YARD-comments.md
Labels: chore

#93 chore: #88 convert pns html to json
  backend/app/controllers/search_controller.rb
  backend/app/services/paknsave_parser.rb
  frontend/src/types/Promo.types.d.ts
Labels: chore

#92 chore: #90 - Log class handles output messaging
  backend/app/controllers/search_controller.rb
  backend/app/helpers/log.rb
  backend/app/services/data_manager.rb
  backend/app/services/new_world_parser.rb
  backend/app/services/web_scraper.rb
Labels: chore
